---
apiVersion: v1
kind: Namespace
metadata:
  name: blue-green
  labels:
    name: blue-green
    purpose: blue-green-deployment
---
apiVersion: v1
kind: Namespace
metadata:
  name: canary
  labels:
    name: canary
    purpose: canary-deployment
